import "/src/app/globals.css";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar/navbar";
import navItems from "./components/Navbar/data";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar items={navItems} />
        {children}
      </body>
    </html>
  );
}
